// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package com.lzh.game.scene.core.jrfa.rpc.entity;

public final class Consistency {
  private Consistency() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WriteRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadRequest_ExtendInfoEntry_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadRequest_ExtendInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021consistency.proto\")\n\014WriteRequest\022\013\n\003k" +
      "ey\030\001 \001(\005\022\014\n\004data\030\002 \001(\014\"\217\001\n\013ReadRequest\022\r" +
      "\n\005group\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\0220\n\nextendInf" +
      "o\030\003 \003(\0132\034.ReadRequest.ExtendInfoEntry\0321\n" +
      "\017ExtendInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\"9\n\010Response\022\014\n\004data\030\001 \001(\014\022\016\n\006er" +
      "rMsg\030\002 \001(\t\022\017\n\007success\030\003 \001(\010B+\n\'com.lzh.g" +
      "ame.scene.core.jrfa.rpc.entityP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WriteRequest_descriptor,
        new String[] { "Key", "Data", });
    internal_static_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadRequest_descriptor,
        new String[] { "Group", "Data", "ExtendInfo", });
    internal_static_ReadRequest_ExtendInfoEntry_descriptor =
      internal_static_ReadRequest_descriptor.getNestedTypes().get(0);
    internal_static_ReadRequest_ExtendInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadRequest_ExtendInfoEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new String[] { "Data", "ErrMsg", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
