// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package com.lzh.game.scene.core.jrfa.rpc.entity;

public interface WriteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WriteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 key = 1;</code>
   */
  int getKey();

  /**
   * <code>bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();
}
